# Generated by Django 5.2.6 on 2025-09-10 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoType',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nums', models.IntegerField()),
                ('special_nums', models.IntegerField(blank=True, null=True)),
                ('has_special', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LottoDraw',
            fields=[
                ('lotto_number', models.CharField(max_length=128)),
                ('lotto_date', models.DateField(primary_key=True, serialize=False)),
                ('lotto_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visualizer.lottotype')),
            ],
        ),
    ]
