# Generated by Django 5.2.6 on 2025-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottodraw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lottodraw',
            name='lotto_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='lottodraw',
            constraint=models.UniqueConstraint(fields=('lotto_date', 'lotto_type'), name='unique_lotto_date_lotto_type'),
        ),
    ]
